{% set version = "0.9.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fst
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fst_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fst/fst_{{ version }}.tar.gz
  sha256: 44c7e889879c2a3a704b70152196e27b6fc1d700062056f9a9c0a49cb98d2665

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-fstcore                    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-fstcore
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-fstcore
    - r-rcpp

test:
  commands:
    - $R -e "library('fst')"           # [not win]
    - "\"%R%\" -e \"library('fst')\""  # [win]

about:
  home: https://fstpackage.github.io
  license: AGPL-3.0-only
  summary: Multithreaded serialization of compressed data frames using the 'fst' format. The 'fst' format allows for random access of stored data and compression with the LZ4 and ZSTD compressors created by Yann Collet. The ZSTD compression library is owned by Facebook Inc.
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - jprnz

# Package: fst
# Type: Package
# Title: Lightning Fast Serialization of Data Frames for R
# Description: Multithreaded serialization of compressed data frames using the 'fst' format. The 'fst' format allows for random access of stored data and compression with the LZ4 and ZSTD compressors created by Yann Collet. The ZSTD compression library is owned by Facebook Inc.
# Version: 0.9.0
# Date: 2019-04-02
# Authors@R: c( person("Mark", "Klik", email = "markklik@gmail.com", role = c("aut", "cre", "cph")), person("Yann", "Collet", role = c("ctb", "cph"), comment = "Yann Collet is author of the bundled LZ4 and ZSTD code and copyright holder of LZ4"), person("Facebook, Inc.", role = "cph", comment = "Bundled ZSTD code"))
# LazyData: true
# Depends: R (>= 3.0.0)
# Imports: Rcpp
# LinkingTo: Rcpp
# SystemRequirements: little-endian platform
# RoxygenNote: 6.1.1
# Suggests: testthat, bit64, data.table, lintr, nanotime, crayon
# License: AGPL-3 | file LICENSE
# Copyright: This package includes sources from the LZ4 library written by Yann Collet, sources of the ZSTD library owned by Facebook, Inc. and sources of the fstlib library owned by Mark Klik
# URL: https://fstpackage.github.io
# BugReports: https://github.com/fstpackage/fst/issues
# NeedsCompilation: yes
# Packaged: 2019-04-02 12:51:58 UTC; Mark
# Author: Mark Klik [aut, cre, cph], Yann Collet [ctb, cph] (Yann Collet is author of the bundled LZ4 and ZSTD code and copyright holder of LZ4), Facebook, Inc. [cph] (Bundled ZSTD code)
# Maintainer: Mark Klik <markklik@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-09 04:43:13 UTC
